#!/bin/bash
#
# Description: Create scaled mask and macro from a virtual slide
# 
# The MIT License (MIT)
# Copyright (c) 2014, UMC Utrecht, B.G.L. Nelissen
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 

# Variables
SCRIPTNAME=$(basename $0)
DESCRIPTIONSHORT="Create scaled mask and macro from a virtual slide"
DEPENDENCIES=("convert" "parallel")
SUPPORTED_FORMATS=("TIFF" "Aperio" "Hamamatsu" "iScan" "iScanHT" "Leica")
DEFAULT_MASKSUFFIX=".mask"
DEFAULT_MACROSUFFIX=".macro"
DEFAULT_MACRO_THUMBSIZE="2000x2000" # Maximum size of macro image
DEFAULT_QSUBARGS="-pe threaded 1 -q veryshort"
DEFAULT_MASKARGS="-blur 40x40 -fuzz 4%"

# Errors go to stderr
err() {
  echo "ERROR: $@" >&2
}
# usage message
usage() {
cat <<- EOF
usage:  
$SCRIPTNAME [options] -f <filename>
Try $SCRIPTNAME --help for more information.
EOF
}
# help message
helpMessage() {
cat <<- EOF
${SCRIPTNAME}: ${DESCRIPTIONSHORT}

usage:
  $SCRIPTNAME [options] -f <filename>

options:
  -f, --file <filename>         virtual slide to create mask from

  [--masksuffix] <text>         mask suffix ["$DEFAULT_MASKSUFFIX"]
  [--macrosuffix] <text>        macro suffix ["$DEFAULT_MACROSUFFIX"]
  [-l, --layer] <integer>       force specific layer by layer id
  [--mask-args] <arguments>     mask arguments (imageMagick) ["$DEFAULT_MASKARGS"]
  
  --help                        display this help
  -h                            display usage

examples:
  $SCRIPTNAME "file.tif"
  $SCRIPTNAME  --file="file.tif"

multiple files at once:
  find "\$(pwd)" -iname "*tif" -exec echo "$(command -v "$SCRIPTNAME")" -f \""{}"\" \;

HPC qsub job submission:
  find "\$(pwd)" -iname "*tif" -type f \\
        -exec printf "qsub $DEFAULT_QSUBARGS " \; \\
        -exec printf "\$(command -v "$SCRIPTNAME") " \; \\
        -exec echo "--file=\""{}"\" " \;

dependencies: ${DEPENDENCIES[@]}
supported formats: ${SUPPORTED_FORMATS[@]}

You can mask parts of your image that you do not wat to process. This
program will use 'convert' to create a mask for you which you can later
edit if needed. The mask is a layer within the original TIF file. The
slideToolkit excludes real black in further processing (color #000000).
Two new files will be created, one file.macro.png, and one masked macro
file (file.mask.png). Definitions of masking can be set with the
--mask-args flag. A blur creates space between the mask and the tissue.
A fuzz selects the background. A fuzz of 3% works well, but fails on
very light slides, a fuzz of 2% is mightby to easy on the selection, 5%
works on slides with a darkish background. Pipe the 'multiple folders at
once' output in 'parallel' for parallel processing. For some slides, the
virtual slide format is not known. For these instances you need to run
slideInfo to find the correct layer manually. When the mask layer is
identified (approximately 2000x2000 pixels), use the --layer flag.

The slideToolkit and all its tools are released under the terms of the MIT license
The slideToolkit (C) 2014, UMC Utrecht, B.G.L. Nelissen
Report issues at https://github.com/bglnelissen/slideToolkit/issues

EOF
}
# Menu
# Empty variables
FILE=""
LAYER=""
MASKSUFFIX=""
MACROSUFFIX=""
MASKARGS=""
# illegal option
illegalOption() {
cat <<- EOF
$SCRIPTNAME: illegal option $1
$(usage)
EOF
exit 1
}
# loop through options
while :
do
  case $1 in
    -h)
      usage
      exit 0 ;;
    --help | -\?)
      helpMessage
      exit 0 ;;
    -f | --file)
      FILE=$2
      shift 2 ;;
    --file=*)
      FILE=${1#*=}
      shift ;;
    -l | --layer)
      LAYER=$2
      shift 2 ;;
    --layer=*)
      LAYER=${1#*=}
      shift ;;
    --masksuffix)
      MASKSUFFIX=$2
      shift 2 ;;
    --masksuffix=*)
      MASKSUFFIX=${1#*=}
      shift ;;
    --mask-args)
      MASKARGS=$2
      shift 2 ;;
    --mask-args=*)
      MASKARGS=${1#*=}
      shift ;;
    --macrosuffix)
      MACROSUFFIX=$2
      shift 2 ;;
    --macrosuffix=*)
      MACROSUFFIX=${1#*=}
      shift ;;
    --) # End of all options
      shift
      break ;;
    -*)
      illegalOption "$1"
      shift ;;
    *)  # no more options. Stop while loop
      break ;;
  esac
done
# DEFAULTS
# set FILE
if [ "$FILE" != "" ]; then
  FILE="$FILE"
else
  FILE="$1"
fi
# set MASKSUFFIX default
if [ "$MASKSUFFIX" != "" ]; then
  MASKSUFFIX="$MASKSUFFIX"
else
  MASKSUFFIX="$DEFAULT_MASKSUFFIX"
fi
# set MASKARGS default
if [ "$MASKARGS" != "" ]; then
  MASKARGS="$MASKARGS"
else
  MASKARGS="$DEFAULT_MASKARGS"
fi
# set MACROSUFFIX default
if [ "$MACROSUFFIX" != "" ]; then
  MACROSUFFIX="$MACROSUFFIX"
else
  MACROSUFFIX="$DEFAULT_MACROSUFFIX"
fi

# requirements
checkRequirements() {
  if ! [[ -f "$FILE" ]] ; then
    err "No such file: $FILE"
    usage
    exit 1
  fi
}

# Dependencies
checkDependencies(){
  DEPS=""
  DEPS_FAIL="0"
  for DEP in ${DEPENDENCIES[@]}; do
    if [[ 0 != "$(command -v "$DEP" >/dev/null ;echo "$?")" ]]; then
       err "Missing dependency: $DEP"
       DEPS_FAIL=$(($DEPS_FAIL + 1))
    fi
  done
  if [[ "$DEPS_FAIL" > 0 ]]; then
    err "Fix missing dependencies (${DEPS_FAIL})"
    usage
    exit 1
  fi
}

# get mask function for each type of scanner
getMacro(){
  # get thumb by layer id
  LAYER="$LAYER"
	convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}
getMacroiScanHT(){
  # layer 8 contains the macro
  LAYER=8
  convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}
getMacroAperio(){
  # the third to last layer contains the macro
  NR_LAYERS=`identify "$FILE" | wc -l`
  LAYER="$(($NR_LAYERS - 3))"
  convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}
getMacroLeica(){
  LAYER=5 # determined from example file (http://openslide.cs.cmu.edu/download/openslide-testdata/)
  convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}
getMacroHamamatsu(){
  LAYER=5 # determined from example file (http://openslide.cs.cmu.edu/download/openslide-testdata/)
  convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}
getMacroiScan(){
  LAYER=7 # determined from example file (http://openslide.cs.cmu.edu/download/openslide-testdata/)
  convert "$FILEFULL[$LAYER]" -resize "${DEFAULT_MACRO_THUMBSIZE}>" -fuzz 1% -transparent "#ECECEC"  "$MACRO"
}

# actual program
programOutput(){
  # set variables
  LAYER="$LAYER"
  FILEFULL="$(echo "$(cd "$(dirname "$FILE")"; pwd)"/"$(basename "$FILE")")" # full path $FULL
  BASENAME="$(basename "$FILEFULL")"    # basename
  EXTENSION="${BASENAME##*.}"         # extension
  FILEPATH="${FILEFULL%.*}"           # full path, no extension
  FILENAME="${BASENAME%.*}"           # filename, no extension"
  MASK="${FILEPATH}${MASKSUFFIX}.png"
  MACRO="${FILEPATH}${MACROSUFFIX}.png"

  # check metadata for scanner data
  if [ "$LAYER" != "" ]; then
    getMacro # layer is set, do it the easy way
  elif [[ "0" < "$(tiffinfo  "$FILEFULL" 2>&1 | strings | grep -i "iScanHT" | wc -l | awk '{print $1}' )" ]]; then
    getMacroiScanHT # iScanHT found
  elif [[ "0" < "$(tiffinfo  "$FILEFULL" 2>&1 | strings | grep -i "Aperio" | wc -l | awk '{print $1}')" ]]; then
    getMacroAperio  # Aperio found
  elif [[ "0" < "$(tiffinfo  "$FILEFULL" 2>&1 | strings | grep -i "Leica" | wc -l | awk '{print $1}')" ]]; then
    getMacroLeica  # Leica found
  elif [[ "0" < "$(tiffinfo  "$FILEFULL" 2>&1 | strings | grep -i "Hamamatsu" | wc -l | awk '{print $1}')" ]]; then
    getMacroHamamatsu  # Hamamatsu found
  elif [[ "0" < "$(tiffinfo  "$FILEFULL" 2>&1 | strings | grep -i "iScan" | wc -l | awk '{print $1}')" ]]; then
    getMacroiScan  # Ventana iScan found
  else    err "Unknown virtual slide format: $FILEFULL"
    err "You probably want to set --layer manually."
    err "Run slideInfo for layer information."
    usage
    exit 1
  fi
  
  # what am I doing here?
  # create mask, lay it ontop of the macro image.
  # a fuzz of 3% works well, but fails on very light slides
  # a fuzz of 2% is mightby to easy on the selection
  # a fuzz of 2.5% is possible (but still to stringend on some slides)
  #	 - add a border so blur works on the whole image
  #	 - blur the image to fill small holes (blur is slow, but necessary)
  #	 - make all white transparent (background)
  #	 - remove the border
  #	 - create alpha and save file
  convert "$MACRO" \( "$MACRO" \
    -bordercolor white -border 100x100 \
    $MASKARGS -transparent white \
    -crop +100+100 -crop -100-100 +repage \
    -alpha extract -transparent white \) \
    -flatten "$MASK"
}
# all check?
checkRequirements
checkDependencies 

# lets go!
# actual program
programOutput