#!/bin/bash
#
# Description: Cut virtual slides into tiles
# Copyright (C) 2014, B.G.L. Nelissen. All rights reserved.
#
################################################################################
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#   Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# 
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
# Respect the Google Shell style guide.
# http://google-styleguide.googlecode.com/svn/trunk/shell.xml

# Variables
SCRIPTNAME=$(basename $0)
DESCRIPTIONSHORT="Cut virtual slides into tiles"
DEPENDENCIES=("convert parallel")
DEFAULTLAYER=3 # 3
DEFAULTHEIGHT=2000
DEFAULTWIDTH=2000
TMPDIR="$(mktemp -d -t slide2Tiles_XXXXXXXXXXXX)"
SLOTS=4
MEMORYLIMIT="$((15 * $SLOTS))GB" # 15 GB per slot


# Errors go to stderr
err() {
  echo "ERROR: $@" >&2
}

# usage message
usage() {
cat <<- EOF
usage:  $SCRIPTNAME [options] [path/]file
        [--help]
EOF
}
# help message
helpMessage() {
cat <<- EOF
${SCRIPTNAME}: ${DESCRIPTIONSHORT}

$(usage)

options:
  -f, --file[=FILE]         virtual slide to create tiles from
  --layer[=INT]             force specific layer [$DEFAULTLAYER]
  --height[=PIXELS]         tile height in pixels [$DEFAULTHEIGHT]
  --width[=PIXELS]          tile width in pixels [$DEFAULTWIDTH]
  
  --help                    display this help and exit

examples:
  $SCRIPTNAME "file.tif"
  $SCRIPTNAME  --file="file.tif"
  find [path/] -name '*.tif' | parallel [path/]slideMask {} 
  find [path/] -name '*.tif' -exec qsub [path/]slideMask {} \; 

dependencies: $DEPENDENCIES

Cut slides into tiles for further processing. Reasonable tile size is
2000 by 2000 pixels (default).

Report bugs to <b.g.l.nelissen@gmail.com>
slideToolkit (C) 2014, B.G.L. Nelissen
EOF
}

# Menu
# Empty variables
FILE=""
LAYER=""
# illegal option
illegalOption() {
cat <<- EOF
$SCRIPTNAME: illegal option $1
$(usage)
EOF
exit 1
}
# loop through options
while :
do
  case $1 in
    --help | -\?)
      helpMessage
      exit 0 ;;
    -f | --file)
      FILE=$2
      shift 2 ;;
    --file=*)
      FILE=${1#*=}
      shift ;;
    --layer=*)
      LAYER=${1#*=}
      shift ;;
    --height=*)
      HEIGHT=${1#*=}
      shift ;;
    --width=*)
      WIDTH=${1#*=}
      shift ;;
    --) # End of all options
      shift
      break ;;
    -*)
      illegalOption "$1"
      shift ;;
    *)  # no more options. Stop while loop
      break ;;
  esac
done

# DEFAULTS
# set FILE default
if [ "$FILE" != "" ]; then
  FILE="$FILE"
else
  FILE="$1"
fi
# set LAYER default
if [ "$LAYER" != "" ]; then
  LAYER="$LAYER"
else
  LAYER="$DEFAULTLAYER"
fi
# set HEIGHT default
if [ "$HEIGHT" != "" ]; then
  HEIGHT="$HEIGHT"
else
  HEIGHT="$DEFAULTHEIGHT"
fi
# set WIDTH default
if [ "$WIDTH" != "" ]; then
  WIDTH="$WIDTH"
else
  WIDTH="$DEFAULTWIDTH"
fi


# requirements
checkRequirements() {
  if ! [[ -f "$FILE" ]] ; then
    echo "No such file: $FILE">&2;
    usage
    exit 1
  fi
  regexnumeric='^[0-9]+$'
  if ! [[ $LAYER =~ $regexnumeric ]] ; then
    echo "Layer is not an integer: $LAYER">&2;
    usage
    exit 1
  fi
  if ! [[ $HEIGHT =~ $regexnumeric ]] ; then
    echo "Height is not valid: $HEIGHT">&2;
    usage
    exit 1
  fi
  if ! [[ $WIDTH =~ $regexnumeric ]] ; then
    echo "Width is not valid: $WIDTH">&2;
    usage
    exit 1
  fi
}

# Dependencies
checkDependencies(){
  DEPENDENCIES="$DEPENDENCIES"
  DEPS=""
  for DEP in $DEPENDENCIES; do
    if [[ 0 != $(command -v "$DEP" >/dev/null ;echo $?) ]]; then
      DEPS=$(echo "$DEPS $DEP") # create `array` with unknown dependencies
    fi
  done
  if [[ "" != $(echo "$DEPS" | perl -p -e 's/ //g') ]]; then
    for d in $DEPS; do
      echo "Missing dependency: \"$d\""
    done
    exit 1
  fi
}

# actual program
programOutput(){
    # set and get variables
    S="$FILE" # input scan
    INPUTFILENAME="${S%.*}"             # full path without extension
    INPUTSCANEXT="${S##*.}"             # input scan extension only
    M="${INPUTFILENAME}.mask.png"       # input mask
    FILENAMESCAN="${S##*/}"
    SHORTNAME="$(basename $INPUTFILENAME)"
    FILENAMEMASK="${M##*/}"
    FOLDERINPUT=$(dirname "$S")         # input folder
    TMPDIR="$TMPDIR"                    # CAREFUL THIS FOLDER GETS DELETED! # CAREFUL WITH THIS MOTHERFUCKER
    FOLDEROUTPUT=$(dirname "$S")        # output directory
    LAYER="$LAYER"                             # layer 3 is 20x (for Roche scanner)
    TILESWIDTH="$WIDTH"
    TILESHEIGHT="$HEIGHT"
    buffer="${TMPDIR}/${SHORTNAME}.mpc"
    STARTDATE=$(date)
      
    # all complete? Lets go
    if [[ -f "$S" && -f "$M" && "tif" == $INPUTSCANEXT ]] ; then
        width=$(identify -format "%w" "${S}[${LAYER}]")
        height=$(identify -format "%h" "${S}[${LAYER}]")
        dimensions=${width}x${height}
        echo "dimensions $dimensions"
        echo "tmpdir : $TMPDIR"
        echo "$(date)"
        echo "Start convert and create big buffer file..."
        convert -limit area ${MEMORYLIMIT} ${S}[${LAYER}] \( ${M} -fuzz 99% -transparent white -scale ${dimensions} -negate \) -composite -fuzz 3% -trim +repage -bordercolor white -border 30x30 +repage ${buffer}
        echo "$(date)"
        echo "Ended convert..."
        echo "Start convert to create bufferexample..."
        # output for user so we know what was in the hpc file
        convert -limit area ${MEMORYLIMIT} ${buffer} -scale "$TILESWIDTH"x"$TILESHEIGHT" ${INPUTFILENAME}.bufferexample.png
        echo "$(date)"
        echo "Ended convert..."# create output directory with similar name as input file
        mkdir -v -p "$INPUTFILENAME" # create output directory
        # create tiles per row, measure dimentions of newly create image
        width=$(identify -format "%w" ${buffer})
        height=$(identify -format "%h" ${buffer})
        dimensions=${width}x${height}
        limit_w=$((($width / $TILESWIDTH)-1))
        limit_h=$((($height / $TILESHEIGHT)-1))
        echo "$(date)"
        echo "Start creating tiles..."
        echo "width      $width"
        echo "height     $height"
        echo "tile width $TILESWIDTH"
        echo "tile height $TILESHEIGHT"
        echo "dimensions $dimensions"
        echo "limit_w    $limit_w"
        echo "limit_h    $limit_h"
        echo "buffer    $buffer"
         for y in $(seq 0 $limit_h); do
             for x in $(seq 0 $limit_w); do
                # one tile
                tile=${SHORTNAME}.X${y}.Y${x}.tile.png
                w=$((x * $TILESWIDTH))
                h=$((y * $TILESHEIGHT))
                FILE="${INPUTFILENAME}/${tile}"
                convert -limit area ${MEMORYLIMIT} ${buffer} -crop ${TILESWIDTH}x${TILESHEIGHT}+$w+$h +repage ${FILE}
                # check for empty tiles
                filenameext=$(basename "$FILE")
                extension="${filenameext##*.}"
                filename="${FILE%.*}" # full path without extension

                # tile checked before?
                CHECKED=${filename##*.} # tissue, empty or something else
                if [ "tissue" == "$CHECKED" ] || [ "empty" == "$CHECKED" ];
                then
                    echo "Already checked: $filenameext"
                    exit
                fi
                
                # find tissue
	            if [ $(wc -c < $FILE ) -ge 100000 ]; then
                    # more than 100000 bytes...
                    VERBOSE=$( convert $FILE -colorspace HSL -verbose info: );
                    RGBO=$( echo "$VERBOSE" | grep mean | awk '{print $2}' )
                    RED=$( echo $RGBO | awk '{print $1}'  | cut -d. -f1 ); 
                    GREEN=$( echo $RGBO | awk '{print $2}'| cut -d. -f1 ); 
                    BLUE=$( echo $RGBO | awk '{print $3}' | cut -d. -f1 );
                    BLUESD=$( echo "$VERBOSE" | grep 'standard deviation' | awk '{print $3}' | sed -n 3p | cut -d. -f1 )
                    if [ $RED -ge 51 ] && [ $GREEN -ge 12 ];
                    then 
                        TISSUE="tissue";
                    elif [ $BLUESD -ge 6 ];
                    then  
                        TISSUE="tissue"; 
                    else
                        TISSUE="empty"; 
                    fi; 
                else 
                    TISSUE="empty"; 
                fi;
                # rename file
                mv -v "$FILE" "${filename}.${TISSUE}.png"
                
             done
         done
        echo "$(date)"
        echo "Ended creating tiles..."
        echo "Remove tmp dir"       
        # $TMPDIR get automatically deleted after each job.
        rm -rfv "$TMPDIR"
    else
        err "No such scan: $S"
        err "No such mask: $M"
        usage
        exit 1
    fi
    STOPDATE=$(date)
}

# all check?
checkRequirements
checkDependencies

# lets go!
programOutput
