#!/bin/bash
#
# Description: Create slide thumbnail, including label
# 
# The MIT License (MIT)
# Copyright (c) 2014, UMC Utrecht, B.G.L. Nelissen
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 

# Variables
SCRIPTNAME=$(basename $0)
DESCRIPTIONSHORT="Create slide thumbnail, including label"
DEPENDENCIES=("convert" "parallel" "perl")
DEFAULT_OUTPUT_SUFFIX=".thumb"
DEFAULT_OUTPUT_EXTENSION="png"
DEFAULT_OUTPUT_DIRECTORY="." # Relative to input file
WIDTH="512"

# DEBUG setting, remove before going live
# set -o verbose

# Errors go to stderr
err() {
  echo "ERROR: $@" >&2
}
# usage message
usage() {
cat <<- EOF
usage:  
$SCRIPTNAME -f <filename> [options]
Try $SCRIPTNAME --help for more information.
EOF
}

# help message
helpMessage() {
cat <<- EOF
${SCRIPTNAME}: ${DESCRIPTIONSHORT}

usage:
  $SCRIPTNAME -f <filename> [options]

options:
  -f, --file <filename>       extract the thumbnail from this virtual slide

  [-l, --layer] <integer>     force specific layer by layer id
  [--suffix] <text>           suffix to filename ("$DEFAULT_OUTPUT_SUFFIX")
  [--extension] <text>        thumbnail output extension ("$DEFAULT_OUTPUT_EXTENSION")
  [--output-dir] <path>       path to output directory
  
  --help                      display this help
  -h                          display usage

examples:
  $SCRIPTNAME "file.svs"
  $SCRIPTNAME  --layer=5 --suffix=".suffix" --extension="jpg" "file.tif"

multiple files at once:
    find ./ -iname "*tif" | parallel "$(command -v "$SCRIPTNAME")" "{}"

HPC qsub job submission:
  for i in \$(find ./ -iname "*tif"); do
    j="\$(echo "\$(cd "\$(dirname "\$i")"; pwd)"/"\$(basename "\$i")")"; \\
    echo "qsub" -pe threaded 1 -q veryshort \\
    "$(command -v "$SCRIPTNAME")" --file="\${j}"
  done

dependencies: ${DEPENDENCIES[@]}

A virtual slide is usually variant of a multilayered/pyramid TIFF file.
Different vendors store an overview of each slide in one (or more) of
these layers. This script extracts the correct layers and resizes,
rotates and concatenates when necessary. By default the thumbnail is
created in the same folder as the original file, a specific output
directory can be set with --output-dir (path can be a relative path or
absolute path) , if the location does not exist it will be created.

The slideToolkit and all its tools are released under the terms of the MIT license
The slideToolkit (C) 2014, UMC Utrecht, B.G.L. Nelissen
Report issues at https://github.com/bglnelissen/slideToolkit/issues

EOF
}

# Menu
# Empty variables
FILE=""
LAYER=""
OUTPUT_SUFFIX=""
OUTPUT_EXTENSION=""
OUTPUT_DIRECTORY=""
# illegal option
illegalOption() {
cat <<- EOF
$SCRIPTNAME: illegal option $1
$(usage)
EOF
exit 1
}
# loop through options
while :
do
  case $1 in
    --help | -\?)
      helpMessage
      exit 0 ;;
    --h)
      usage
      exit 0 ;;
    -f | --file)
      FILE=$2
      shift 2 ;;
    -l | --layer)
      LAYER=$2
      shift 2 ;;
    --layer=*)
      LAYER=${1#*=}
      shift ;;
    --file=*)
      FILE=${1#*=}
      shift ;;
    --suffix)
      OUTPUT_SUFFIX=$2
      shift 2;;
    --suffix=*)
      OUTPUT_SUFFIX=${1#*=}
      shift ;;
    --extension)
      OUTPUT_EXTENSION=$2
      shift 2;;
    --extension=*)
      OUTPUT_EXTENSION=${1#*=}
      shift ;;
    --output-dir)
      OUTPUT_DIRECTORY=$2
      shift 2;;
    --output-dir=*)
      OUTPUT_DIRECTORY=${1#*=}
      shift ;;
    --) # End of all options
      shift
      break ;;
    -*)
      illegalOption "$1"
      shift ;;
    *)  # no more options. Stop while loop
      break ;;
  esac
done
# DEFAULTS
# set FILE default
if [ "$FILE" != "" ]; then
  FILE="$FILE"
else
  FILE="$1"
fi

# set OUTPUT_SUFFIX default
if [ "$OUTPUT_SUFFIX" != "" ]; then
  OUTPUT_SUFFIX="$OUTPUT_SUFFIX"
else
  OUTPUT_SUFFIX="$DEFAULT_OUTPUT_SUFFIX"
fi
# set OUTPUT_EXTENSION default
if [ "$OUTPUT_EXTENSION" != "" ]; then
  OUTPUT_EXTENSION="$OUTPUT_EXTENSION"
else
  OUTPUT_EXTENSION="$DEFAULT_OUTPUT_EXTENSION"
fi
# set OUTPUT_DIRECTORY default
if [ "$OUTPUT_DIRECTORY" != "" ]; then
  OUTPUT_DIRECTORY="$OUTPUT_DIRECTORY"
else
  OUTPUT_DIRECTORY="$DEFAULT_OUTPUT_DIRECTORY"
fi

# requirements
checkRequirements() {
  if ! [[ -f "$FILE" ]] ; then
    err "No such file: $FILE"
    usage
    exit 1
  fi
}

# Dependencies
checkDependencies(){
  DEPS=""
  DEPS_FAIL="0"
  for DEP in ${DEPENDENCIES[@]}; do
    if [[ 0 != "$(command -v "$DEP" >/dev/null ;echo "$?")" ]]; then
       err "Missing dependency: $DEP"
       DEPS_FAIL=$(($DEPS_FAIL + 1))
    fi
  done
  if [[ "$DEPS_FAIL" > 0 ]]; then
    err "Fix missing dependencies (${DEPS_FAIL})"
    usage
    exit 1
  fi
}

# get thumb for each scanner type
getThumbiScanHT(){
  if [ "$LAYER" != "" ]; then
    LAYER="$LAYER"
  else
    # layer 0 contains the thumb
    LAYER=0
  fi
	convert "$FILEFULL[$LAYER]" "$OUTPUTFILENAME"
}
getThumbAperio(){
  if [ "$LAYER" != "" ]; then
    convert "$FILEFULL"[$LAYER] "$OUTPUTFILENAME"
  else
    # the last 2 layers contain thumb and the tissue (couning starts at 0)
    NR_LAYERS=`identify "$FILE" | wc -l`
    N_LABEL="$(($NR_LAYERS - 2))"
    N_TISSUE="$(($NR_LAYERS - 1))"
    # get label, get tissue, rotate one and resize both, then append 
    convert "$FILEFULL[$N_LABEL]" -resize "$WIDTH"x \( "$FILEFULL[$N_TISSUE]" -rotate 90 -resize "$WIDTH"x \) -append "$OUTPUTFILENAME"
  fi
}

programOutput(){
  # set variables
  FILE="$FILE"
  # path variables
  FILEFULL="$(echo "$(cd "$(dirname "$FILE")"; pwd)"/"$(basename "$FILE")")" # full path $FULL
  DIRFULL="$(echo "$(cd "$(dirname "$FILE")"; pwd)")"
  BASENAME="$(basename "$FILEFULL")"    # basename
  DIRNAME="$(dirname "$FILE")"          # dirname
  EXTENSION="${BASENAME##*.}"           # extension
  FILEPATH="${FILEFULL%.*}"             # full path, no extension
  FILENAME="${BASENAME%.*}"             # filename, no extension"
  # Check if path to OUTPUT_DIRECTORY is absolute or relative
  if [[ "$OUTPUT_DIRECTORY" = /* ]]
  then
   # Absolute path is found, use it
   OUTPUT_DIRECTORY_PATH="$OUTPUT_DIRECTORY"
  else
   # Relative path
   OUTPUT_DIRECTORY_PATH="${DIRFULL}/${OUTPUT_DIRECTORY}"
  fi
  # Create the path if it does not exist
  mkdir -p "$OUTPUT_DIRECTORY_PATH"
  # The final path for the output file is:
  OUTPUTFILENAME="${OUTPUT_DIRECTORY_PATH}/${FILENAME}${OUTPUT_SUFFIX}.${OUTPUT_EXTENSION}"
  
  # check metadata for scanner data
  if [[ "0" < "$(tiffinfo  "$FILE" | strings | grep "iScanHT" | wc -l)" ]]; then
    getThumbiScanHT # iScanHT found
  elif [[ "0" < "$(tiffinfo  "$FILE" | strings | grep "Aperio" | wc -l)" ]]; then
    getThumbAperio  # Aperio found
  else
    err "Unknown virtual slide format: $FILE"
    usage
    exit 1
  fi
}

# all check?
checkRequirements
checkDependencies

# lets go!
programOutput
