#!/bin/bash
#
# Description: Convert virtual slide to pyramid TIFF format
# Copyright (C) 2014, B.G.L. Nelissen. All rights reserved.
#
#
# License here
#
# Respect the Google Shell style guide.
# http://google-styleguide.googlecode.com/svn/trunk/shell.xml

echo "This script is not yet operational"