# run: conda env create -f conda3_8_cp413.v1.yml
# run: conda env update -f conda3_8_cp413.v1.yml
# run: conda env remove -n cp4
name: cp4

channels:
- defaults
- bioconda
- miniconda
- conda-forge

dependencies:
- python==3.8
- pip
- numpy==1.*
- matplotlib
- pandas
- openjdk
- scikit-learn
- mahotas
- gtk2
- gtk3
- Jinja2==3.*
- inflect==5.*
- wxpython==4.*
- mysqlclient==1.*
- sentry-sdk==0.18.*
- centrosome
- gensim
- FuzzyTM
- xarray
- python-javabridge
- bftools
- cairo
- freetype
- gettext
- giflib
- imagemagick
- java-jdk
- jpeg
- wmctrl
- zbar
- tclap
- pip:
    - cellprofiler==4.1.3
    - arrow
    - pathlib
    - opencv-contrib-python
    - openslide-python>=1.1.2
    
# you could automatically provide the prefix, or just do it via the prompt
# prefix: ~/miniconda3/envs/cp4

# prefix: /Users/[username]/miniconda3/envs/cp4
